name: Report a Technical/Visual Issue in the Science Center Project
description: 'Is something not working as expected? Did you encounter a glitch or a bug with the project?'
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue you've found in the Science Center project. Please fill in the template below. If
        unsure about something, just do as best as you're able. If you are reporting a visual glitch, it will be much
        easier for us to fix it when you attach a screenshot as well.
  - type: input
    attributes:
      label: 'URL:'
      description: The URL of the page you are reporting an issue on.
      placeholder: https://https://ehharding.github.io/science-center/en/
    validations:
      required: true
  - type: input
    attributes:
      label: 'Browser Name:'
      description: What kind of browser are you using?
      placeholder: Chrome
    validations:
      required: true
  - type: input
    attributes:
      label: 'Browser Version:'
      description: What browser version are you using?
      placeholder: '103.0.5060.134'
    validations:
      required: true
  - type: input
    attributes:
      label: 'Operating System:'
      description: What kind of operation system are you using? (Write it in full, with version number)
      placeholder: 'Windows 11 Pro, 23H2, 22631.3672'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Steps to Reproduce:'
      placeholder: |
        1. What I did.
        2. What I expected to happen.
        3. What I actually got.
        4. If possible, images or videos are welcome.
    validations:
      required: true
